#!/usr/bin/env python3
"""
Generates single-file framework references for every framework version under
framework/v*/ and writes them to versions/<version>.md.
"""

from pathlib import Path
import re

REPO_ROOT = Path(__file__).resolve().parent.parent
FRAMEWORK_BASE = REPO_ROOT / "framework"
OUTPUT_DIR = REPO_ROOT / "versions"


def parse_version_dir_name(name: str):
    match = re.match(r"^v(\d+)(?:\.(\d+))?$", name)
    if not match:
        return None
    major = int(match.group(1))
    minor = int(match.group(2) or 0)
    return (major, minor)


def list_framework_versions() -> list[Path]:
    version_dirs: list[Path] = []
    if not FRAMEWORK_BASE.exists():
        return version_dirs

    for path in FRAMEWORK_BASE.iterdir():
        if not path.is_dir():
            continue
        version = parse_version_dir_name(path.name)
        if version is None:
            continue
        version_dirs.append(path)

    return sorted(version_dirs, key=lambda p: (parse_version_dir_name(p.name), p.name))


def list_spec_files(version_root: Path) -> list[Path]:
    def parse_prefix(name: str):
        numeric = re.match(r"^(\d+)_", name)
        if numeric:
            return (0, int(numeric.group(1)), name)

        onboarding = re.match(r"^OB_(\d+)_", name)
        if onboarding:
            return (1, int(onboarding.group(1)), name)

        # Non-prefixed names come last, then lexical.
        return (2, 0, name)

    def path_sort_key(path: Path):
        rel = path.relative_to(version_root)
        # Keep root files first, then commands/, then prompts/, then others.
        top = rel.parts[0]
        if len(rel.parts) == 1:
            section_rank = 0
        elif top == "commands":
            section_rank = 1
        elif top == "prompts":
            section_rank = 2
        else:
            section_rank = 3

        return (section_rank, *parse_prefix(path.name), rel.as_posix())

    files = [path for path in version_root.rglob("*.md") if path.is_file()]
    return sorted(files, key=path_sort_key)


def merge_one(version_root: Path):
    include_files = list_spec_files(version_root)
    output_file = OUTPUT_DIR / f"{version_root.name}.md"

    with open(output_file, "w", encoding="utf-8") as out:
        out.write("# ragnor.dev Specs — Single File Reference\n\n")
        out.write(
            "This file is a concatenation of framework Markdown files under "
            f"`framework/{version_root.name}/`.\n"
            "It is generated by `merge_specs_v1.py` and intended for AI agent consumption.\n"
            "Do not edit this file directly — edit the source files under "
            f"`framework/{version_root.name}/`.\n\n"
        )
        out.write("---\n\n")

        for file_path in include_files:
            rel_path = file_path.relative_to(REPO_ROOT).as_posix()
            out.write(f"<!-- SOURCE: {rel_path} -->\n\n")
            out.write(file_path.read_text(encoding="utf-8").strip())
            out.write("\n\n---\n\n")

    print(f"Generated: {output_file} ({len(include_files)} files)")


def merge():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    version_dirs = list_framework_versions()
    if not version_dirs:
        raise SystemExit(f"No framework version directories found in {FRAMEWORK_BASE}")

    for version_root in version_dirs:
        merge_one(version_root)


if __name__ == "__main__":
    merge()
